{
 "title": "Bits-EnergyMonitor",
 "description": "BITS SES Assignment - Smart energy monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Power Ch - 2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SMARTENERGY\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r.channel == \"2\" and r._field == \"power_W\")\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Power Ch - 4",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SMARTENERGY\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r.channel == \"4\" and r._field == \"power_W\")\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Power Ch- 6",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SMARTENERGY\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r.channel == \"6\" and r._field == \"power_W\")\n  |> yield(name: \"_results\")"
    }
   ]
  },
  { "title": "System Alert", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 } },
  {
   "title": "Line Current",
   "type": "timeseries",
   "description": "Individual Current",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"SMARTENERGY\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"scaled_value\")\n  |> yield(name: \"_results\")\n"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"SMARTENERGY\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"energy_kWh\")\n  |> yield(name: \"_results\")\n\n\n"
    }
   ]
  }
 ]
}